### ISSUE TITLE
Prozessausgabe

### ISSUE THREAD

**Issue by MrDNA3712** [Layviz/WindowsReparaturTool#3]
Eine Frage an den Nutzer, ob man die Ausgabe der Prozesse sehen will.

**Comment by MrDNA3712** [comment]
wenn man die ausgabe sehen will, soll sich ein extra fenster (ein Fenster für alle Prozesse) dafür öffnen.
das Fenster soll offen bleiben solange das hauptfenster offen ist.

**Comment by Layviz** [comment]
to toggle output select the mode with plus sign e.g. 1+

**Comment by Layviz** [comment]
use just + or - to toggle for all following scans

**Comment by MrDNA3712** [comment]
also add #11 and #12 to this
